CREATE TABLE HR.EVENTS  (	
 EVENT_ID NUMBER(6,0), 
 EVENT_DATE DATE, 
 EVENT_TITLE VARCHAR2(256), 
 CONSTRAINT EVENT_ID_PK PRIMARY KEY (EVENT_ID)
  ) 
  
  CREATE SEQUENCE HR.events_seq;
  
select * from hr.events;

CREATE TABLE HR.Persons  (	
 PERSON_ID NUMBER(6,0), 
 AGE NUMBER, 
 FIRST_NAME VARCHAR2(256), 
 LAST_NAME VARCHAR2(256),
 CONSTRAINT PERSONS_ID_PK PRIMARY KEY (PERSON_ID)
  ) 
  
  CREATE SEQUENCE HR.persons_seq;
  
  CREATE TABLE HR.PERSON_EVENT
  (
    PERSON_ID NUMBER(6,0),
    EVENT_ID NUMBER(6,0), 
    CONSTRAINT PERSON_EVENT_PK PRIMARY KEY (PERSON_ID, EVENT_ID),
    CONSTRAINT PERSON_ID_FK FOREIGN KEY (PERSON_ID) REFERENCES HR.Persons(PERSON_ID),
    CONSTRAINT EVENT_ID_FK FOREIGN KEY (EVENT_ID) REFERENCES HR.EVENTS(EVENT_ID)   
  )
  
  select * from hr.persons
   select * from hr.person_event